# <div style="text-align: center;">NumPy</div>

## Table of contents: 
* **What are Arrays or Python Arrays?**
* **List vs Array**
* **Numpy Library**
* **Uses of Numpy Library**
* **Numpy Array**
* **Creating a Numpy arrary**
* **Basic Numpy Opration**
* **Some Numpy Library Funcations**
* **Indexing and Slicing**
* **Mathematical Operations**
* **Basic Array Oprations**
* **References**

## What are Arrays or Python Arrays? 
Arrays are a fundamental data structure, and an important part of most programming languages. In Python, they are containers which are able to store more than one item at the same time. Specifically, they are **an ordered collection of elements** with every value being of the **same data type**

The idea is to **store multiple items of the same type together**. Unlike Python lists (can store elements of mixed types), arrays must have all elements of same type. Having only homogeneous elements makes it **memory-efficient.**

**Python Array is the build in array in python**

In [10]:
import array as arr #import array module

a = arr.array('i', [1, 2, 3]) # creating array from a list; 
# `'i'` is a type code that specifies the data type of the elements in the array.The `'i'` type code represents signed integers.

print(a)  

print(a[0]) # accessing First Araay

print(a[1]) # accessing Second Araay

a.append(5) # Adding element to array

print(a)  

array('i', [1, 2, 3])
1
2
array('i', [1, 2, 3, 5])


In [14]:
a

array('i', [1, 2, 3, 5])

In [8]:
a[0]

1

In [9]:
a[2]

3

In [10]:
a[-1]

5

In [16]:
a.append(10)
a

array('i', [1, 2, 3, 5, 10])

## List vs Array

![](listvsarray.png)

🔸 1. Data Types
List:
Can contain elements of different data types (e.g., integers, strings, floats in the same list).

Array:
All elements must be of the same data type (e.g., all integers or all floats).

🔸 2. Module Import
List:
No need to import any module; lists are built-in in Python.

Array:
Requires importing the array module using import array.

🔸 3. Arithmetic Operations
List:
Cannot directly perform arithmetic operations like addition or multiplication element-wise.

Array:
Can directly handle arithmetic operations, making it useful for numeric tasks.

🔸 4. Preferred Use Case
List:
Better for shorter sequences or mixed-type data.

Array:
Ideal for long sequences of numerical data.

🔸 5. Flexibility
List:
Very flexible — supports easy modification, insertion, deletion, etc.

Array:
Less flexible — changes must be done element-wise, which is more manual.

🔸 6. Printing
List:
Can be printed directly using print(my_list).

Array:
Requires a loop or specific handling to print or access each element.

🔸 7. Memory Usage
List:
Uses more memory because it stores additional information (e.g., type info).

Array:
More compact and memory-efficient, especially for large numeric datasets.

🔸 8. Operations and Built-in Functions
List:
Offers many built-in functions (e.g., count(), sort(), max(), min(), sum(), index(), append(), remove()) — and no imports needed.

Array:
Requires proper modules and typecodes to perform similar operations.

## NumPy

NumPy is a popular library in Python which is used for scientific and numerical computing, especially for array manipulation. It provides powerful features that allow users to manipulate large arrays and matrices efficiently.

It is a fundamental tool in the field of data science, scientific computing, and machine learning and is widely used by researchers, data scientists, and developers for a wide range of applications. 



## Uses of NumPy

![](usesOfNumpy.jpg)

![](Applications-of-NumPy.jpg)

### Numpy forms the basis of these python libraries:
* **Scientific Computing & Data Analysis: Pandas, SciPy**
* **Machine Learning & Deep Learning: Scikit-learn, TensorFlow, PyTorch**
* **Visualization: Matplotlib, Seaborn, Plotly**

## NumPy Array

NumPy arrays are a part of the NumPy library, which is a powerful tool for numerical computing in Python. These arrays are designed for high-performance operations on large volumes of data and support multi-dimensional arrays and matrices. This makes them ideal for complex mathematical computations and large-scale data processing.

**Key Features:**
* **Multi-dimensional support:** NumPy arrays can handle more than one dimension, making them suitable for matrix operations and more complex mathematical constructs.
* **Broad broadcasting capabilities:** They can perform operations between arrays of different sizes and shapes, a feature known as broadcasting.
* **Efficient storage and processing:** NumPy arrays are stored more efficiently than Python lists and provide optimized performance for numerical operations.

![](numpyArray.png)

## Example of 2D Numpy Array:

In GIS, a 2D NumPy array is commonly used to store surface elevation data for a single layer over a spatial grid — like a Digital Elevation Model (DEM).

🔹 Example Scenario:
You're storing land surface elevation data over:


* 20 latitude points,

* 30 longitude points.

**So, the array shape is: (20, 30)**


(lat, lon) → (20, 30)

## Example of 4D Numpy Array:

Here's a simple example of a 4D NumPy array in a climate modeling context:

🔹 Example Scenario:
You're storing temperature data over:

* 10 time steps (e.g., days),

* 5 pressure levels (e.g., vertical atmospheric layers),

* 20 latitude points,

* 30 longitude points.

**So, the array shape is: (10, 5, 20, 30)**


(time, level, lat, lon) → (10, 5, 20, 30)


## Create a numpy array

In [36]:
#Import Numpy Library

import numpy

In [38]:
# create a numpy array(1D)

arr = numpy.array([1,2,3,4,5]) # create a 1D numpy array named arr using a list


In [40]:
#print the arr array

print(arr) #print the arr array

[1 2 3 4 5]


In [42]:
#print the arr array without using print function 

arr

array([1, 2, 3, 4, 5])

In [10]:
#Import Numpy Library as np(since it is a universal convension of importing numpy library)

import numpy as np

In [55]:
# create a 1D numpy array(from a list)

arr = np.array([1,2,3,4,5]) # create a 1D Numpy array named arr using a list

print(arr) #print the arr array

arr #or simply writing the name of the array without writing print function

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

## The Basics(This section covers the ndim, shape, size, and dtype attributes of an array)

In [64]:
print(type(arr)) #print the type of the arr

print(arr.dtype) #print data type of the elements and describes how the bytes in the fixed-size block of memory corresponding to an array item

print(arr.size) #no of items

print(arr.shape) #size of array or matrix

print(arr.ndim) #dimension of the array(1D,2D,3D)

<class 'numpy.ndarray'>
int64
5
(5,)
1


In [70]:
# int64:  "int" for integer, "64" for 64-bit. 
# int64 refers to a 64-bit integer data type. 
#int64 signifies that it uses 64 bits of memory to store the integer value.

#### You can display outputs in Python without using the print() function

In [62]:
type(arr)

numpy.ndarray

In [32]:
arr.size


5

In [33]:

arr.shape


(5,)

In [34]:

arr.ndim

1

In [35]:
# create a 2D numpy array(2x5)(from a list)

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

print(type(arr)) #print the type of arr 

print(arr.dtype) #A data type object describes how the bytes in the fixed-size block of memory corresponding to an array item

print(arr.size) #no of items

print(arr.shape) #size of array or matrix(R,C)

print(arr.ndim) #dimension of the array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
int64
10
(2, 5)
2


In [36]:
# create a 2D numpy array (3x4)(from a list)

arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [1,2,3,4,5]]) #Rows must have same number of items

print(arr)

print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
2


In [37]:
# Creating a 3D array of shape (2, 3, 4)
arr3D = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],
                   [[13, 14, 15, 16],[17, 18, 19, 20],[21, 22, 23, 24]]])

In [38]:
arr3D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [39]:
arr3D.shape

(2, 3, 4)

In [40]:
arr3D.ndim

3

In [41]:
# create a arranged numpy array from 1 to 10

arr = np.arange(1,10) #arr = np.arange(min,max)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [42]:
#create square zero matrix
arr = np.zeros(5, int) #arr = np.zeros(size, int)
print(arr)

[0 0 0 0 0]


In [43]:
#create non-square zero matrix
arr = np.zeros([5,3]) #arr = np.zeros(row, col)
print(arr)

print(arr.ndim) #dimension of the array

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [187]:
#create square one matrix
arr = np.ones(5) #by default float
print(arr)

[1. 1. 1. 1. 1.]


In [189]:
#create square one matrix
arr = np.ones(5, int) #arr = np.zeros(size, int), have to mention datatype 
print(arr)

[1 1 1 1 1]


In [185]:
#create square one matrix
arr = np.ones([5, 4],int) #arr = np.zeros(size, int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [44]:
# create a identity matrix
arr = np.eye(4) #identity matrix is a square a matrix
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
# create a diagonal matrix
arr = np.diag([2,3,4,5])
print(arr)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [46]:
# creating numpy array with random numbers
arr = np.random.rand(5)
print(arr)

[0.57969911 0.56215119 0.99344744 0.25057984 0.84827312]


In [12]:
# creating numpy array with random numbers(with min,max and number)
arr = np.random.randint(0,50,10) # arr = np.random.randint(min, max, number/shape)
print(arr)

[ 0 39  5 34 49 44 32 43 40 13]


In [21]:
# creating 2D numpy array with random numbers(with min,max and size )
arr2D = np.random.randint(0,50,(4,4)) # arr = np.random.randint(min, max, shape)
print(arr2D)

[[47 30  8  5]
 [42 44 42  5]
 [37 44  4  4]
 [35  8  5 33]]


# Using some library functions

In [50]:
# creating numpy array with random numbers(with min,max and number)
arr = np.random.randint(0,20,10) # arr = np.random.randint(min, max, number)
print(arr)

[ 8 15 17  6  4 19  9 17  1 12]


In [51]:
# finding maximum value
max = arr.max()
print(max)

19


In [52]:
#access nth item or indexing
n=arr[5]
print(n)

#alternative
print(arr[5])

19
19


## Indexig & Slicing 

In [54]:
#slicing an array or access nth to n'th items of an array
print(arr[2:5]) # index 2 to 4

[17  6  4]


In [55]:
print(arr[:5]) # index o to 4

[ 8 15 17  6  4]


In [56]:
print(arr[:]) # whole array

[ 8 15 17  6  4 19  9 17  1 12]


In [57]:
# creating 2D numpy array with random numbers(with min,max and size )
arr2D = np.random.randint(0,20,(4,4)) # arr = np.random.randint(min, max, number)
print(arr2D)

[[17 12  5 19]
 [10  8  5  0]
 [ 0 17 10 13]
 [11 11  1 13]]


In [58]:
#Access an item from a 2D array 

print(arr2D[1][2]) #print(arr2D[row][col])

#or simply

arr2D[1][2] #without using print() function

5


5

In [59]:
#Access an item or element from a 2D array 

print(arr2D[0][2]) #print(arr2D[row][col])

#or simply

arr2D[0][2]


5


5

In [60]:
#Alternative
#Access an item or element from a 2D array 

print(arr2D[0,2]) #print(arr2D[row, col])

#or simply

arr2D[0,2]


5


5

In [61]:
#access nth row
print(arr2D[0,:]) #access 1st row or index o row # : > means all rows of that row are selected

#or
print(arr2D[0]) #access 1st row or index o row

[17 12  5 19]
[17 12  5 19]


In [62]:
#access nth col
#print(arr2D[r,c])

print(arr2D[:,0]) #access 1st col or index o col # : > means all rows of that column are selected


[17 10  0 11]


In [63]:
print(arr2D[1]) #access 2st row or index 1 row

[10  8  5  0]


In [64]:
# Accessing two columns (e.g., 1st and 3rd columns)
selected_columns = arr2D[:, [0,2]]

print(selected_columns)


[[17  5]
 [10  5]
 [ 0 10]
 [11  1]]


In [65]:
# Alternative1 
# Accessing two columns (e.g., 1st and 3rd columns)
cols = [0, 2]  # Indices of the columns you want
selected_columns = arr2D[:, cols]

print(selected_columns)


[[17  5]
 [10  5]
 [ 0 10]
 [11  1]]


In [66]:
# Alternative 2
# Accessing two columns (e.g., 1st and 3rd columns or index o and 2)

print(arr2D[:, [0,2]])

[[17  5]
 [10  5]
 [ 0 10]
 [11  1]]


In [67]:
# creating 2D numpy array with random numbers(with min,max and size )
arr2D = np.random.randint(0,20,(4,4)) # arr = np.random.randint(min, max, number)
print(arr2D)

[[14 16 11  4]
 [19  9  8  8]
 [ 6 12  6  2]
 [13 13 12  8]]


In [68]:
# Accessing or slicing an array from an array

print(arr2D[0:3, 0:3]) # 1st to 2nd row and 1st to 2nd row


[[14 16 11]
 [19  9  8]
 [ 6 12  6]]


## Mathemtics 

## Basic array operations

In [70]:
arr=np.array([[1,2,3,4],[5,6,7,8], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [71]:
 print(arr+arr)

[[ 2  4  6  8]
 [10 12 14 16]
 [10 12 14 16]]


![](02.05-broadcasting.png)

![](broadcasting.png)

In [72]:
arr+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [ 7,  8,  9, 10]])

In [73]:
arr*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [10, 12, 14, 16]])

In [74]:
arr/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [2.5, 3. , 3.5, 4. ]])

In [157]:
arr1=np.array([[2,2,2,2],[3,3,3,3],[4,4,4,4]])
arr1

array([[2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [76]:
arr1.shape

(2, 4)

In [165]:
arr2=np.array([[2,2],[2,2],[2,2],[2,2]])
arr2

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [78]:
arr2.shape

(4, 2)

In [79]:
arr1*arr1

array([[4, 4, 4, 4],
       [9, 9, 9, 9]])

In [141]:
arr2*arr2

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [177]:
print(arr1)
arr1.shape

[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


(3, 4)

In [167]:
print(arr2)
arr2.shape

[[2 2]
 [2 2]
 [2 2]
 [2 2]]


(4, 2)

In [173]:
arrdot=np.dot(arr1,arr2)
arrdot

array([[16, 16],
       [24, 24],
       [32, 32]])

In [179]:
arrdot.shape

(3, 2)

# References: 

1. [List vs Array](https://www.geeksforgeeks.org/difference-between-list-and-array-in-python/)
2. [Numpy application](https://pythongeeks.org/numpy-applications/)
3. [Numpy documentation](https://numpy.org/doc/2.2/user/absolute_beginners.html)
